// values-v2.js
// Values mapped to archetype keys from card-art-v2.jsx.
// Archetype families per visual-direction CSV (Sheet1):
//   GS = Geometric/Structured  OF = Organic Form
//   EM = Energetic Mark        PM = Painterly Mark
// Format: [name, archetypeKey, blurb, prompt]

window.VALUES = [
  // A
  ["Acceptance",         "ripples",     "Letting it be what it is — fully, without fixing.", "What am I refusing to make peace with?"],
  ["Accessibility",      "door",        "The door propped open on purpose. Welcome wider than you have to.", "Whose access did I take for granted today?"],
  ["Accomplishment",     "spark",       "The thing you set out to do, finished. Quiet pride.", "What have I done that I haven't let myself feel proud of?"],
  ["Accountability",     "plumb",       "Owning my piece of it. The buck stops with me.", "What am I dodging responsibility for?"],
  ["Accuracy",           "grid",        "Telling the truth on time, in detail, on purpose.", "Where am I rounding off when I should be exact?"],
  ["Achievement",        "streak",      "Reaching the marker — and noticing you reached it.", "Which win am I overdue to celebrate?"],
  ["Activeness",         "streak",      "Movement over waiting. Motion makes the path.", "Where am I waiting for permission I could just give myself?"],
  ["Adaptability",       "branch",      "Bending instead of breaking. New shape, same self.", "What change am I refusing to roll with?"],
  ["Adventure",          "path",        "Leaving the map at home on purpose.", "When did I last say yes to something unfamiliar?"],
  ["Aesthetics",         "gradient",    "Beauty as a working principle, not a luxury.", "What around me deserves more care than it's getting?"],
  ["Agility",            "triangle",    "Quick on your feet. Light on your turn.", "What would I do faster if I trusted myself more?"],
  ["Ambition",           "starburst",   "Wanting more — out loud, on purpose.", "What do I want that I haven't said out loud?"],
  ["Appreciation",       "leaf",        "Noticing the good without inflating it.", "Who deserves a thank-you I keep forgetting to send?"],
  ["Assertiveness",      "plumb",       "Saying it plainly. Standing where you stand.", "What have I been softening to keep the peace?"],
  ["Authenticity",       "brushstroke", "The match between inside and outside.", "Where am I performing instead of being?"],
  ["Awareness",          "concentric",  "Seeing the room, including yourself in it.", "What did I almost miss today?"],
  // B
  ["Balance",            "balance",     "Both/and, not either/or. Weight distributed.", "What's currently tipping too far?"],
  ["Beauty",             "gradient",    "The world dressed up. Worth slowing down for.", "What did I find beautiful this week?"],
  ["Boldness",           "spark",       "Stepping out before you know if it'll work.", "Where would I move if I weren't waiting?"],
  ["Bravery",            "streak",      "Doing the thing while the fear is still here.", "What's the next brave inch?"],
  ["Brilliance",         "sun",         "Light leaking out of the work. Hard to fake.", "Where does my brilliance show up uninvited?"],
  // C
  ["Calmness",           "ripples",     "The settled water that lets you see the bottom.", "What would calm me down if I let it?"],
  ["Celebration",        "dots",        "Marking the moment. Refusing to skip past joy.", "What's worth marking that I'm tempted to skip?"],
  ["Change",             "wave",        "The version of you that doesn't exist yet.", "What is changing in me that I haven't named?"],
  ["Charity",            "bowl",        "Giving without keeping the receipt.", "What can I give that costs me a little?"],
  ["Cheerfulness",       "splash",      "Bringing the weather with you.", "Whose day could I make a little lighter?"],
  ["Clarity",            "ring",        "The fog lifts and the shape shows up.", "What would become obvious if I sat still long enough?"],
  ["Cleverness",         "pyramid",     "Seeing the angle nobody else clocked.", "Where could a smarter approach replace a harder one?"],
  ["Collaboration",      "venn",        "The thing you couldn't make alone.", "Who would I rather build this with?"],
  ["Commitment",         "handshake",   "All-in, on the record, with your name on it.", "What am I half-in on that wants my whole self?"],
  ["Community",          "trio",        "The people whose chairs have your name on them.", "Where am I most at home, around whom?"],
  ["Compassion",         "flower",      "Feeling with, not just feeling for.", "Whose situation am I writing off too quickly?"],
  ["Competence",         "pyramid",     "Knowing how, plus knowing you know how.", "What have I gotten quietly good at?"],
  ["Confidence",         "ladder",      "Standing in your own posture.", "Where do I shrink that I don't have to?"],
  ["Conformity",         "grid",        "Fitting the pattern on purpose.", "Where is fitting in costing me too much?"],
  ["Connection",         "venn",        "Threads between people that hold weight.", "Who have I not called this month?"],
  ["Consistency",        "grid",        "Same person, every day, no matter the room.", "Where am I one person Monday and another Friday?"],
  ["Contentment",        "dot",         "Enough — and noticing it's enough.", "What would I stop chasing if I let myself?"],
  ["Cooperation",        "handshake",   "Same boat, both rowing.", "Where am I rowing alone when I don't have to?"],
  ["Courage",            "flame",       "Doing the thing while afraid.", "Where am I careful when I should be brave?"],
  ["Creativity",         "inkbleed",    "Making something that wasn't there.", "What wants to be made through me?"],
  ["Curiosity",          "spiral",      "Following the question further than the answer.", "What have I been quietly curious about?"],
  // D
  ["Daring",             "slash",       "Calling your own bluff.", "What dare have I been ducking?"],
  ["Decisiveness",       "balance",     "Choosing, then living the choice.", "What decision am I dragging out?"],
  ["Dignity",            "plumb",       "Treating yourself like you matter — and meaning it.", "Where do I let myself be diminished?"],
  ["Directness",         "plumb",       "Saying the thing, plainly, today.", "What do I need to say without the wrapping?"],
  ["Discipline",         "grid",        "Keeping the appointment with yourself.", "Which promise to myself am I dropping?"],
  ["Discovery",          "eye",         "Finding what was already there, waiting.", "What would I find if I went looking?"],
  ["Diversity",          "trio",        "Difference as the source of strength.", "Whose viewpoint am I missing in the room?"],
  ["Drive",              "streak",      "The engine that keeps going.", "What's pulling me forward right now?"],
  ["Duty",               "shield",      "What you do because it's yours to do.", "What's mine to carry that I keep handing off?"],
  // E
  ["Education",          "ladder",      "Climbing, one rung of understanding at a time.", "What do I want to know more about — really?"],
  ["Efficiency",         "grid",        "More done, less spent.", "What am I doing the long way out of habit?"],
  ["Empathy",            "embrace",     "Standing in their weather for a minute.", "Whose feelings have I been too busy to feel?"],
  ["Energy",             "starburst",   "The juice. The fire under it.", "What gives me energy that I keep saving for later?"],
  ["Entertainment",      "flick",       "Lightness on purpose. Permission to play.", "What do I do for fun that I've stopped doing?"],
  ["Equality",           "balance",     "Same starting line, same rules, same dignity.", "Where am I treating people unequally without meaning to?"],
  ["Excellence",         "pyramid",     "Caring about the thing the way it deserves.", "What am I willing to do badly long enough to do well?"],
  ["Expertise",          "grid",        "Years of paying attention, made portable.", "What have I learned that I should be teaching?"],
  ["Expression",         "brushstroke", "Putting the inside out.", "What's in me that's waiting to be said?"],
  // F
  ["Fairness",           "balance",     "Same scales for everyone, including me.", "Where am I bending the rules in my favour?"],
  ["Faith",              "arc",         "Walking forward without all the proof.", "What am I trusting will hold?"],
  ["Family",             "trio",        "The people who know my whole shape.", "Who in my family have I been avoiding?"],
  ["Femininity",         "flower",      "A particular kind of strength. Soft, not weak.", "What about my softness do I undervalue?"],
  ["Fulfilment",         "ring",        "Whole, not finished.", "When do I feel most whole?"],
  ["Fierceness",         "flame",       "Tender on the inside, sharp at the edges.", "Where am I being too gentle with what's mine?"],
  ["Financial Stability","coin",        "Not anxious about the basics.", "What money worry needs a real plan, not more thinking?"],
  ["Flexibility",        "wave",        "Bending where the situation asks.", "Where am I being rigid out of habit?"],
  ["Focus",              "concentric",  "One thing, fully, until it's done.", "What deserves my full attention this week?"],
  ["Forgiveness",        "embrace",     "Letting it down so my hands are free.", "Who am I still carrying a grudge for?"],
  ["Frankness",          "plumb",       "Saying it, kindly and plainly.", "What conversation am I overdue?"],
  ["Freedom",            "wings",       "Room to choose my own days.", "What would I drop if I trusted I'd be okay?"],
  ["Friendship",         "handshake",   "The standing appointment.", "Which friendship am I letting drift?"],
  ["Fun",                "splash",      "Permission to be silly, soft, undefended.", "What makes me laugh that I keep forgetting to do?"],
  // G
  ["Generosity",         "bowl",        "Open hands, on purpose, often.", "Where could I give more than is strictly required?"],
  ["Gratitude",          "sun",         "Noticing it before it's gone.", "What am I grateful for that I haven't said?"],
  ["Growth",             "seedstack",   "Becoming, not arriving.", "Who will I be a year from now if I keep going?"],
  // H
  ["Happiness",          "dots",        "Not the destination — the temperature.", "What dependably warms me?"],
  ["Harmony",            "venn",        "Different notes, same chord.", "Where is my life out of tune?"],
  ["Health",             "leaf",        "The body, kept.", "What is my body asking for that I keep ignoring?"],
  ["Heroism",            "streak",      "Showing up when it costs you something.", "Where could I be the help I'm waiting for?"],
  ["Honour",             "shield",      "Doing right when nobody's watching.", "What promise am I keeping in private?"],
  ["Making a Difference","ripples",     "A dent shaped like you.", "What's the dent I want to leave?"],
  ["Home",               "tree",        "The place that lets you exhale.", "Where do I exhale fully?"],
  ["Honesty",            "plumb",       "Truth on time, to me first.", "What am I pretending not to know?"],
  ["Hopefulness",        "arc",         "Betting on the better version.", "What am I quietly hopeful about?"],
  ["Hospitality",        "door",        "Making room. A chair for one more.", "Whose welcome have I been forgetting?"],
  ["Humility",           "dot",         "Not smaller — just rightly sized.", "Where am I making it about me?"],
  ["Humor",              "squiggle",    "Lightness as medicine.", "What do I find funny that I've stopped letting myself enjoy?"],
  // I
  ["Initiative",         "spark",       "Starting before someone asks.", "What needs to start that no one's started?"],
  ["Integrity",          "plumb",       "One self, all the rooms.", "Where am I two different people?"],
  ["Imagination",        "inkbleed",    "Seeing what isn't there yet.", "What if I let myself dream bigger?"],
  ["Independence",       "plumb",       "Standing on my own legs, by choice.", "Where am I waiting for someone to do it for me?"],
  ["Inspiration",        "spark",       "The match that lights other matches.", "Who lights me up, and have I told them?"],
  ["Innovation",         "grid",        "A better way that wasn't here before.", "What process around me is begging to be redesigned?"],
  ["Intelligence",       "eye",         "Quick to see, slow to assume.", "Where could thinking better replace working harder?"],
  ["Inventiveness",      "starburst",   "Making the tool for the job that didn't exist.", "What am I reinventing that wants to be invented?"],
  ["Intuition",          "spiral",      "The knowing under the knowing.", "What does my gut keep saying that I keep overruling?"],
  // J
  ["Joy",                "dots",        "Catching delight on the way past.", "What's making me smile that I'm not noticing?"],
  ["Justice",            "balance",     "The right thing, even when it's the hard thing.", "Where am I staying quiet when I should speak?"],
  // K
  ["Kindness",           "heart",       "The soft answer, the easy hand.", "Whose week could I make easier?"],
  ["Knowledge",          "ladder",      "What you've learned, made yours.", "What do I know that I should be using more?"],
  // L
  ["Leadership",         "crown",       "Going first, with care for who follows.", "Where am I being asked to lead and I'm hiding?"],
  ["Learning",           "ladder",      "The student stance, kept.", "What am I learning right now — really?"],
  ["Legacy",             "ripples",     "What outlives the doing.", "What do I want to leave behind?"],
  ["Leisure",            "ripples",     "Time without an agenda.", "When is the next stretch of nothing on my calendar?"],
  ["Love",               "heart",       "The choice you keep making.", "Who am I loving well, and who needs more?"],
  ["Loyalty",            "shield",      "Standing in their corner — even now.", "Whose corner am I in, and have I shown up?"],
  // M
  ["Mastery",            "pyramid",     "The 10,000th time, on purpose.", "What craft is calling for another decade?"],
  ["Maturity",           "tree",        "The version of you that learned.", "What old reaction is no longer mine?"],
  ["Mindfulness",        "concentric",  "Here, on purpose, in the body.", "What's true for me right now?"],
  ["Motivation",         "streak",      "The reason that gets me out of bed.", "What's pulling me — and is it still pulling?"],
  // N
  ["Nature",             "leaf",        "Outside on purpose. Often.", "When did I last put my hands in the dirt?"],
  // O
  ["Open‑mindedness","spiral",     "Leaving the door cracked.", "What view am I refusing to even consider?"],
  ["Openness",           "arc",         "Available to be changed.", "What am I closed to that wants in?"],
  ["Optimism",           "arc",         "Betting on it working out.", "What am I dreading that might actually be fine?"],
  ["Order",              "grid",        "A place for it, and it in the place.", "What's chaotic that wants tidying?"],
  ["Originality",        "brushstroke", "Sounding like me, not like a copy of me.", "Where am I sanding off my own edges?"],
  // P
  ["Passion",            "flame",       "The fire that doesn't need feeding.", "What lights me up that I keep dimming?"],
  ["Patience",           "ripples",     "Letting the bread rise.", "Where am I rushing what wants time?"],
  ["Perfection",         "ring",        "Whole, not flawless.", "Where is perfect getting in the way of done?"],
  ["Perseverance",       "streak",      "One more step, when steps run out.", "Where do I quit too early?"],
  ["Persuasiveness",     "arrowup",     "Bringing them with you, not over you.", "What do I believe that I haven't made the case for?"],
  ["Playfulness",        "squiggle",    "Permission to mess about.", "Where could I take it less seriously?"],
  ["Power",              "slash",       "The voltage that's mine to use.", "Where am I underusing my own power?"],
  ["Pragmatism",         "grid",        "What works, today, in this room.", "Where am I waiting for the perfect plan?"],
  ["Pride",              "crown",       "Standing tall in the work.", "What am I proud of that I haven't said?"],
  ["Privacy",            "lock",        "A door I get to close.", "What of mine am I oversharing?"],
  ["Proactivity",        "spark",       "Doing it before it's a problem.", "What's becoming a problem I could nip now?"],
  ["Professionalism",    "grid",        "Bringing your best stranger to the room.", "Where am I being too casual with what matters?"],
  ["Purposefulness",     "compass",     "Doing this on purpose, not by drift.", "Why am I doing this — really?"],
  // R
  ["Recognition",        "sun",         "Being seen for it.", "Whose work needs witnessing right now?"],
  ["Reflection",         "crescent",    "Looking back so the path is visible.", "What is the past month trying to tell me?"],
  ["Reliability",        "grid",        "Word given, word kept.", "Whose trust am I cashing without restocking?"],
  ["Resilience",         "mountain",    "Bending and bouncing back.", "What have I survived that I haven't credited myself for?"],
  ["Resourcefulness",    "branch",      "Making do, then making more.", "What do I already have that I'm not using?"],
  ["Respect",            "balance",     "Making room for who someone is.", "Whose dignity have I bruised lately?"],
  ["Responsibility",     "shield",      "It's mine. I'll handle it.", "What's mine that I keep giving back?"],
  ["Risk Taking",        "slash",       "Skin in, eyes open.", "What's a smart risk I've been ducking?"],
  // S
  ["Sacrifice",          "bowl",        "The thing given up so the bigger thing can stand.", "What am I unwilling to give up — and is that costing me?"],
  ["Safety",             "shield",      "Solid ground under the feet.", "Where do I feel most safe — and why?"],
  ["Security",           "shield",      "Steady enough to plan from.", "What kind of security am I actually after?"],
  ["Self‑control",  "lock",        "Pause before the impulse runs the show.", "What impulse keeps running me?"],
  ["Self‑discipline","grid",       "Doing it because I said I would.", "Which standard am I letting slide?"],
  ["Self‑reliance", "plumb",       "I've got me, first.", "What am I waiting on others to do for me that I could do?"],
  ["Self‑respect",  "plumb",       "Treating myself like the friend I'd like to be.", "How would I treat me if I respected me more?"],
  ["Serenity",           "ripples",     "The deep quiet under the noise.", "What stills me?"],
  ["Service",            "bowl",        "Hands off myself long enough to hold someone else.", "Whose load could I lighten this week?"],
  ["Sharing",            "venn",        "Yours, mine, ours.", "What of mine could I more freely share?"],
  ["Simplicity",         "dot",         "Less, on purpose.", "What could I subtract today?"],
  ["Speed",              "streak",      "Quick where it counts.", "Where would faster be better than perfect?"],
  ["Spirituality",       "spiral",      "Bigger than me, including me.", "When do I feel part of something larger?"],
  ["Spontaneity",        "flick",       "Yes, before the brain talks me out of it.", "What did I almost do that I should have done?"],
  ["Stability",          "tree",        "Roots that hold through weather.", "What in my life is rooted enough?"],
  ["Status",             "crown",       "Position, earned and worn lightly.", "What am I chasing for status that doesn't actually fit?"],
  ["Strength",           "pyramid",     "Solid where it counts.", "Where am I stronger than I give myself credit for?"],
  ["Success",            "streak",      "The marker reached, the next one set.", "What does success actually look like to me?"],
  ["Sustainability",     "leaf",        "A pace that lasts.", "What's draining me unsustainably?"],
  // T
  ["Teamwork",           "venn",        "We, and meaning it.", "Whose work am I treating as separate that isn't?"],
  ["Time",               "hourglass",   "The non-renewable. The point.", "What's worth my hours that I'm not giving them to?"],
  ["Tradition",          "tree",        "The handed-down, kept.", "What of my inheritance is worth keeping?"],
  ["Transcendence",      "arc",         "Bigger than the small self.", "Where do I lose myself in the good way?"],
  ["Travel",             "path",        "New rooms, new weather.", "Where do I want to wake up that I haven't?"],
  ["Trust",              "handshake",   "Hands extended, on the strength of so far.", "Who has earned my trust that I'm withholding it from?"],
  // U
  ["Uniqueness",         "brushstroke", "Sounding like me. Only.", "What about me have I been told to tone down?"],
  // V
  ["Variety",            "trio",        "Many flavours, one life.", "What new thing wants in?"],
  ["Vision",             "compass",     "Where this is all going.", "What does the long horizon look like?"],
  ["Vulnerability",      "smudge",      "The brave act of being seen.", "What truth am I afraid to share?"],
  ["Vitality",           "sun",         "Lit up. In the body. Awake.", "What makes me feel most alive?"],
  // W
  ["Warmth",             "gradient",    "The fire kept for others, too.", "Whose day could I warm up?"],
  ["Wealth",             "coin",        "Enough, plus some to share.", "What does enough actually look like?"],
  ["Wellbeing",          "leaf",        "Looked after. From the inside out.", "What's one practice that puts me right?"],
  ["Wholeheartedness",   "brushstroke", "All of me, in.", "What am I doing half-heartedly that deserves all of me?"],
  ["Wonder",             "starburst",   "Refusing to flatten the world.", "What did I notice today that I almost didn't?"],
];
